<!-- html -->
<template>
  <n-space>
    <n-button disabled>默认按钮</n-button>
    <n-button
      type="primary"
      disabled
    >主要按钮</n-button>
    <n-button
      type="success"
      disabled
    >成功按钮</n-button>
    <n-button
      type="danger"
      disabled
    >危险按钮</n-button>
    <n-button
      type="warning"
      disabled
    >警告按钮</n-button>
    <n-button
      type="dashed"
      disabled
    >虚线按钮</n-button>
    <n-button
      type="text"
      disabled
    >文本按钮</n-button>
  </n-space>
  <n-space>
    <n-button
      round
      disabled
    >默认按钮</n-button>
    <n-button
      type="primary"
      round
      disabled
    >主要按钮</n-button>
    <n-button
      type="success"
      round
      disabled
    >成功按钮</n-button>
    <n-button
      type="danger"
      round
      disabled
    >危险按钮</n-button>
    <n-button
      type="warning"
      round
      disabled
    >警告按钮</n-button>
    <n-button
      type="dashed"
      round
      disabled
    >虚线按钮</n-button>
    <n-button
      type="text"
      round
      disabled
    >文本按钮</n-button>
  </n-space>
</template>