<!-- html -->
<template>
  <n-space>
    <n-button leftIcon="m-icon-complete">按钮</n-button>
    <n-button
      type="primary"
      size="small"
      leftIcon="m-icon-add-circle"
    >添加</n-button>
    <n-button
      type="success"
      leftIcon="m-icon-home"
    >主页</n-button>
    <n-button
      type="danger"
      rightIcon="m-icon-calendar"
    >日历</n-button>
    <n-button
      type="warning"
      leftIcon="m-icon-upload"
    >上传</n-button>
    <n-button
      type="dashed"
      rightIcon="m-icon-search"
    >搜索</n-button>
    <n-button
      type="text"
      leftIcon="m-icon-ashbin"
      style="color: #ec3437"
    >删除</n-button>
  </n-space>
  <n-space>
    <n-button leftIcon="m-icon-electronics"></n-button>
    <n-button
      type="primary"
      size="small"
      leftIcon="m-icon-edit"
    ></n-button>
    <n-button
      type="success"
      size="mini"
      leftIcon="m-icon-add-circle"
    ></n-button>
    <n-button
      type="danger"
      round
      leftIcon="m-icon-collection"
    ></n-button>
    <n-button
      type="warning"
      round
      leftIcon="m-icon-calendar"
    ></n-button>
    <n-button
      type="dashed"
      round
      leftIcon="m-icon-upload"
    ></n-button>
    <n-button
      type="text"
      leftIcon="m-icon-ashbin"
      style="color: #ec3437"
    ></n-button>
  </n-space>
</template>