<!-- html -->
<template>
  <n-space>
    <n-button>默认大小</n-button>
    <n-button type="primary">默认大小</n-button>
    <n-button
      type="success"
      size="medium"
    >中等大小</n-button>
    <n-button
      type="danger"
      size="medium"
    >中等大小</n-button>
    <n-button
      type="warning"
      size="small"
    >小型按钮</n-button>
    <n-button
      type="dashed"
      size="mini"
    >超小按钮</n-button>
    <n-button
      type="text"
      size="mini"
    >超小按钮</n-button>
  </n-space>
  <n-space>
    <n-button round>默认大小</n-button>
    <n-button
      type="primary"
      round
    >默认大小</n-button>
    <n-button
      type="success"
      round
      size="medium"
    >中等大小</n-button>
    <n-button
      type="danger"
      round
      size="medium"
    >中等大小</n-button>
    <n-button
      type="warning"
      round
      size="small"
    >小型按钮</n-button>
    <n-button
      type="dashed"
      round
      size="mini"
    >超小按钮</n-button>
  </n-space>
</template>