<!-- html -->
<template>
  <n-space>
    <n-button
      type="custom"
      customColor="#9935f5"
    >自定义颜色</n-button>
    <n-button
      type="custom"
      customColor="#1ba7dd"
    >自定义颜色</n-button>
    <n-button
      type="custom"
      round
      customColor="#d33cc7"
    >自定义颜色</n-button>
    <n-button
      type="custom"
      round
      customColor="#0008ff"
      icon="m-icon-spinner6"
      localing
      disabled
    >自定义颜色</n-button>
  </n-space>
</template>